<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>local</groupId><artifactId>xlat</artifactId><version>1</version>
  <dependencies>
    <dependency>
      <groupId>info.cqframework</groupId>
      <artifactId>cql-to-elm</artifactId>
      <version>3.26.0</version>
    </dependency>
    <dependency>
      <groupId>info.cqframework</groupId>
      <artifactId>elm-jackson</artifactId>
      <version>3.26.0</version>
    </dependency>
    <dependency>
      <groupId>info.cqframework</groupId>
      <artifactId>quick</artifactId>
      <version>3.26.0</version>
    </dependency>
    <dependency>
      <groupId>info.cqframework</groupId>
      <artifactId>model-jackson</artifactId>
      <version>3.26.0</version>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-nop</artifactId>
      <version>2.0.13</version>
    </dependency>
  </dependencies>
</project>
